- name: Deploy SSH keys on CoreOS hosts
  hosts: coreos
  gather_facts: False
  roles:
    - coreos-bootstrap
    - { role: coreos-authorized_keys, group: admins }


- name: Deploy SSH keys for root
  hosts: shell-servers
  become: true
  tasks:
  - block:
    - command: mktemp /root/.ssh/authorized_keys.XXXXX
      register: tmpfile

    - authorized_key:
        user: root
        path: "{{ tmpfile.stdout }}"
        key: "{{ users[item].get('key') or lookup('file', 'files/keys/' + item + '.pub') }}"
      with_items: "{{ user_groups.admins }}"

    - command: mv {{ tmpfile.stdout }} /root/.ssh/authorized_keys

    rescue:
    - file:
        path: "{{ tmpfile.stdout }}"
        state: absent
    - fail: msg="Failed to deploy SSH keys for root"
