- name: Push SSH keys to all CoreOS servers
  hosts: coreos
  sudo: no
  tasks:
  # TODO: Remove the backup if there was no change
  - name: Backup authorized_keys file
    shell: cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys-$(date '+%Y%m%d-%H%M')

  - name: Deploy (most) keys
    authorized_key: user=core key="{{ item }}"
    with_file:
    - keys/kf.pub

  - name: Deploy keys restricted to hashbang.sh
    authorized_key:
      user: "core"
      key: "{{ item }}"
      key_options: 'from="*.hashbang.sh"'
    with_file:
    - keys/kf_hashbang.pub