---
- hosts: mail.hashbang.sh
  become: true
  tasks:
#    # Does not work on CoreOS, due to the fucked up
#    # Python install and lack of installable packages.
#    - name: Start the ircd container
#      docker_container:
#        name: postfix
#        state: started

    - name: Generating aliases
      template:
        src: files/postfix/aliases.j2
        dest: /home/core/postfix/config/aliases
      notify: [rehash aliases]

    - name: Copy static configuration
      copy:
        src: "{{ item }}"
        dest: /home/core/postfix/config/{{ item | basename }}
      with_fileglob:
        - postfix/*.cf
      notify: [reload config]

  # Handlers are executed in the order they are written
  handlers:
    - name: rehash aliases
      command: docker exec postfix newaliases

    - name: reload config
      command: docker exec postfix postfix reload
