---
- name: Pull latest /etc files
  hosts: shell-servers
  become: true
  tasks:
  - command: etckeeper vcs pull --ff-only
    register: etc_result
    changed_when: "'Already up-to-date' not in etc_result.stdout"
  - command: etckeeper init
    when: etc_result.changed

- name: Update/Sync system packages
  hosts: shell-servers
  become: true
  tasks:
  - apt: update_cache=yes
  - shell: apt-cache dumpavail | dpkg --update-avail
  - shell: dpkg --clear-selections
  - shell: dpkg --set-selections < /etc/packages.txt
  - shell: apt-get dselect-upgrade -qy
    environment:
      DEBIAN_FRONTEND: noninteractive
  - apt: upgrade=dist
  - shell: aptitude purge -y -q ~c
    environment:
      DEBIAN_FRONTEND: noninteractive
  - shell: apt-get clean

- name: "Update #! python packages"
  hosts: shell-servers
  become: true
  tasks:
  - pip: name='git+https://github.com/hashbang/provisor/'    editable=False state=latest
  - pip: name='git+https://github.com/hashbang/hashbangctl/' editable=False state=latest
