- name: Pull latest /etc files on all servers
  hosts: shell-servers
  sudo: yes
  tasks:
  - shell: git pull chdir=/etc --ff-only

- name: Update/Sync system packages across all servers
  hosts: shell-servers
  sudo: yes
  tasks:
  - apt: update_cache=yes
  - apt: upgrade=dist
  - shell: awk '{print $1}' /etc/packages.txt | xargs aptitude install -y -q
  - shell: apt-get install -y -q -t unstable selinux-policy-default
  - shell: executable=/bin/bash diff <(dpkg --get-selections) <(cat /etc/packages.txt) | grep -E '^<' | awk '{ print $2 }' | xargs apt-get remove -y -q
  - shell: aptitude purge -y -q ~c

- name: update #! python packages to all servers
  hosts: shell-servers
  sudo: yes
  tasks:
  - pip: name='git+https://github.com/hashbang/provisor/#egg=provisor'
  - pip: name='git+https://github.com/hashbang/hashbangctl/#egg=hashbangctl'
