---

- name: Deploy SSH keys for root
  hosts: shell-servers
  become: true
  tasks:
  - block:
    - command: mktemp /root/.ssh/authorized_keys.XXXXX
      register: tmpfile

    - authorized_key:
        user: root
        path: "{{ tmpfile.stdout }}"
        key: "{{ users[item].key }}"
      when: users[item].key is defined
      with_items: "{{ user_groups.admins }}"
    - authorized_key:
        user: root
        path: "{{ tmpfile.stdout }}"
        key: "{{ lookup('file', 'files/keys/' + item + '.pub') }}"
      when: users[item].key is not defined
      with_items: "{{ user_groups.admins }}"

    - command: mv {{ tmpfile.stdout }} /root/.ssh/authorized_keys

    rescue:
    - file:
        path: "{{ tmpfile.stdout }}"
        state: absent
    - fail: msg="Failed to deploy SSH keys for root"


- name: Pull latest /etc files
  hosts: shell-servers
  become: true
  tasks:
  - command: etckeeper vcs pull --ff-only
    register: etc_result
    changed_when: etc_result.stdout == "Already up-to-date.\n"
  - command: etckeeper init
    when: etc_result.changed

- name: Update/Sync system packages
  hosts: shell-servers
  become: true
  tasks:
  - apt: update_cache=yes
  - shell: apt-cache dumpavail | dpkg --update-avail
  - shell: dpkg --clear-selections
  - shell: dpkg --set-selections < /etc/packages.txt
  - shell: apt-get dselect-upgrade -qy
    environment:
      DEBIAN_FRONTEND: noninteractive
  - apt: upgrade=dist
  - shell: aptitude purge -y -q ~c
    environment:
      DEBIAN_FRONTEND: noninteractive

- name: "Update #! python packages"
  hosts: shell-servers
  become: true
  tasks:
  - pip: name='git+https://github.com/hashbang/provisor/'    editable=False state=latest
  - pip: name='git+https://github.com/hashbang/hashbangctl/' editable=False state=latest
