# -*- eval: (ansible) -*-
- name: Load data from vault
  hosts: "{{ hosts | default('all') }}"
  gather_facts: False
  tasks:
    - include_vars:
        dir: vault/{{ item }}
      with_items: "{{ load.split(',') }}"
