# -*- eval: (ansible) -*-
- include: ../vault.yml load=ldap hosts=shell_servers,ldap.hashbang.sh,hashbang.sh

- name: Set LDAP password for provisor
  hosts: ldap.hashbang.sh
  gather_facts: False
  tasks:
    - ldap_passwd:
        server_uri: ldaps://ldap.hashbang.sh
        bind_dn: "{{ ldap.admin.dn }}"
        bind_pw: "{{ ldap.admin.password }}"

        dn: "{{ ldap.provisor.dn }}"
        passwd: "{{ ldap.provisor.password }}"
      delegate_to: localhost

- name: Deploy hashbangctl.conf
  hosts: shell_servers
  tasks:
    - template:
        src: ../files/hashbangctl.conf.j2
        dest: /etc/hashbangctl.conf
        mode: 0640
        owner: root
        group: root

- name: Deploy provisor password to www.hashbang.sh
  hosts: hashbang.sh
  become: False
  tasks:
    - copy:
        dest: /home/core/hashbang.sh/env
        mode: 0644
        content: |
          LDAP_PASSWORD={{ ldap.provisor.password }}
      notify: restart www

  handlers:
    - name: restart www
      become: True
      service:
        name: hashbangsh
        state: restarted
